import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import CustomCursor from "@/components/CustomCursor";
import ScrollToTop from "@/components/ScrollToTop";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

const neueHaas = localFont({
  src: [
    {
      path: "../public/fonts/NeueHaasUnica-Light-393b7755bb1e04800aca7388c3034b03730538a1edb91af0775d5b2bf99e9976.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-neue-haas",
});

const romie = localFont({
  src: [
    {
      path: "../public/fonts/Romie-Bold-37564e629265ef25685f80fc45af952d2005bef04719bf73894062d1027dcb62.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-romie",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${neueHaas.variable} ${romie.variable} antialiased`}
        suppressHydrationWarning
      >
        <CustomCursor />
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
